// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: resource.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JwksRefresh_Refresh_FullMethodName = "/agentgateway.dev.resource.JwksRefresh/Refresh"
)

// JwksRefreshClient is the client API for JwksRefresh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JwksRefresh lets a data plane ask the control plane for an immediate refetch of a
// remote JWKS the control plane pushed inline (`JWTProvider.remote_jwks_key`). A data
// plane calls it when a token names a key id the pushed set does not have, which is
// what a signing-key rotation of the issuer looks like between two scheduled fetches.
// The control plane fetches at most once per key within a short interval whatever the
// number of callers, pushes a changed set through the normal policy update, and answers
// with the set it holds so the request that asked can be validated at once.
type JwksRefreshClient interface {
	Refresh(ctx context.Context, in *JwksRefreshRequest, opts ...grpc.CallOption) (*JwksRefreshResponse, error)
}

type jwksRefreshClient struct {
	cc grpc.ClientConnInterface
}

func NewJwksRefreshClient(cc grpc.ClientConnInterface) JwksRefreshClient {
	return &jwksRefreshClient{cc}
}

func (c *jwksRefreshClient) Refresh(ctx context.Context, in *JwksRefreshRequest, opts ...grpc.CallOption) (*JwksRefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JwksRefreshResponse)
	err := c.cc.Invoke(ctx, JwksRefresh_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JwksRefreshServer is the server API for JwksRefresh service.
// All implementations must embed UnimplementedJwksRefreshServer
// for forward compatibility.
//
// JwksRefresh lets a data plane ask the control plane for an immediate refetch of a
// remote JWKS the control plane pushed inline (`JWTProvider.remote_jwks_key`). A data
// plane calls it when a token names a key id the pushed set does not have, which is
// what a signing-key rotation of the issuer looks like between two scheduled fetches.
// The control plane fetches at most once per key within a short interval whatever the
// number of callers, pushes a changed set through the normal policy update, and answers
// with the set it holds so the request that asked can be validated at once.
type JwksRefreshServer interface {
	Refresh(context.Context, *JwksRefreshRequest) (*JwksRefreshResponse, error)
	mustEmbedUnimplementedJwksRefreshServer()
}

// UnimplementedJwksRefreshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJwksRefreshServer struct{}

func (UnimplementedJwksRefreshServer) Refresh(context.Context, *JwksRefreshRequest) (*JwksRefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedJwksRefreshServer) mustEmbedUnimplementedJwksRefreshServer() {}
func (UnimplementedJwksRefreshServer) testEmbeddedByValue()                     {}

// UnsafeJwksRefreshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JwksRefreshServer will
// result in compilation errors.
type UnsafeJwksRefreshServer interface {
	mustEmbedUnimplementedJwksRefreshServer()
}

func RegisterJwksRefreshServer(s grpc.ServiceRegistrar, srv JwksRefreshServer) {
	// If the following call panics, it indicates UnimplementedJwksRefreshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JwksRefresh_ServiceDesc, srv)
}

func _JwksRefresh_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JwksRefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwksRefreshServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JwksRefresh_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwksRefreshServer).Refresh(ctx, req.(*JwksRefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JwksRefresh_ServiceDesc is the grpc.ServiceDesc for JwksRefresh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JwksRefresh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentgateway.dev.resource.JwksRefresh",
	HandlerType: (*JwksRefreshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Refresh",
			Handler:    _JwksRefresh_Refresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource.proto",
}
